// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMRjXdWs9imDKqdehc7zKj2KUb5HfJwO0',
    appId: '1:441665247130:web:d13296fb2e5ede3fbb8c23',
    messagingSenderId: '441665247130',
    projectId: 'fluttermedsystem',
    authDomain: 'fluttermedsystem.firebaseapp.com',
    storageBucket: 'fluttermedsystem.appspot.com',
    measurementId: 'G-3QY78BW7BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQVF90EhJEWpNv80Op1aSTPzs8FcwvpAc',
    appId: '1:441665247130:android:9512fde207135529bb8c23',
    messagingSenderId: '441665247130',
    projectId: 'fluttermedsystem',
    storageBucket: 'fluttermedsystem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATbc8LPT-WfPJ7gHOg-RVmiEt_Z4UXPuM',
    appId: '1:441665247130:ios:991b6712c84fae79bb8c23',
    messagingSenderId: '441665247130',
    projectId: 'fluttermedsystem',
    storageBucket: 'fluttermedsystem.appspot.com',
    iosBundleId: 'com.example.medsystemApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATbc8LPT-WfPJ7gHOg-RVmiEt_Z4UXPuM',
    appId: '1:441665247130:ios:991b6712c84fae79bb8c23',
    messagingSenderId: '441665247130',
    projectId: 'fluttermedsystem',
    storageBucket: 'fluttermedsystem.appspot.com',
    iosBundleId: 'com.example.medsystemApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMRjXdWs9imDKqdehc7zKj2KUb5HfJwO0',
    appId: '1:441665247130:web:47c1cc8bc91de85dbb8c23',
    messagingSenderId: '441665247130',
    projectId: 'fluttermedsystem',
    authDomain: 'fluttermedsystem.firebaseapp.com',
    storageBucket: 'fluttermedsystem.appspot.com',
    measurementId: 'G-72K33NX67Y',
  );
}
